import { vi } from 'vitest';

// DB をモック（統合テストはDB不要）
vi.mock('@maestro/db', () => ({
  getDb: vi.fn(() => ({
    select: vi.fn().mockReturnThis(),
    from: vi.fn().mockReturnThis(),
    where: vi.fn().mockReturnThis(),
    limit: vi.fn().mockResolvedValue([]),
    insert: vi.fn().mockReturnThis(),
    values: vi.fn().mockResolvedValue(undefined),
    transaction: vi.fn().mockImplementation((fn: (tx: unknown) => Promise<unknown>) => fn({
      insert: vi.fn().mockReturnThis(),
      values: vi.fn().mockResolvedValue(undefined),
    })),
    execute: vi.fn().mockResolvedValue([]),
  })),
  closeDb: vi.fn(),
  companies: {},
  users: {},
  company_memberships: {},
  board_api_keys: {},
  agent_api_keys: {},
  agents: {},
  issues: {},
  issue_comments: {},
  goals: {},
  projects: {},
  cost_events: {},
  budget_policies: {},
  routines: {},
  approvals: {},
  approval_comments: {},
  activity_log: {},
  plugins: {},
  plugin_config: {},
  agent_handoffs: {},
  agent_task_sessions: {},
  session_summaries: {},
  plugin_jobs: {},
  plugin_job_runs: {},
  plugin_webhooks: {},
  memories: {},
  webhooks: {},
  notifications: {},
  heartbeat_runs: {},
  issue_goals: {},
  jobs: {},
  join_requests: {},
  artifacts: {},
  note_articles: {},
  note_article_images: {},
  playbooks: {},
  playbook_steps: {},
  playbook_jobs: {},
  recipes: {},
  recipe_steps: {},
  settings: {},
  search_index: {},
  user_profiles: {},
  session_context: {},
}));
