import { exec } from 'child_process';
import { promisify } from 'util';
import { createGzip } from 'zlib';
import {
  createReadStream,
  createWriteStream,
  existsSync,
  mkdirSync,
  unlinkSync,
  writeFileSync,
} from 'fs';
import { pipeline } from 'stream/promises';
import { join, basename } from 'path';
import { homedir } from 'os';
import { google } from 'googleapis';
import { createGdriveAuth } from './gdrive.js';

const execAsync = promisify(exec);
const BACKUP_DIR = join(homedir(), '.maestro', 'backups');

const PG_CONTAINER = 'maestro-postgres';
const PG_USER = 'maestro';
const PG_DB = 'maestro';

export interface BackupRunConfig {
  destinationType: string;
  compression?: string;
  gdriveFolderId?: string;
  localPath?: string;
  language?: string;
}

export interface BackupRunResult {
  success: boolean;
  filePath?: string;
  driveUrl?: string;
  manualDriveUrl?: string;
  message: string;
}

/** リカバリマニュアルを生成する */
function generateRecoveryManual(backupFileName: string, createdAt: Date, language = 'ja'): string {
  const locale = language === 'zh' ? 'zh-CN' : language === 'en' ? 'en-US' : 'ja-JP';
  const timeZone = 'Asia/Tokyo';
  const dateStr = createdAt.toLocaleString(locale, {
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
    timeZone,
  });
  const isGzip = backupFileName.endsWith('.gz');
  const restoreCmd = isGzip
    ? `gunzip -c "${backupFileName}" | docker exec -i maestro-postgres psql -U maestro maestro`
    : `docker exec -i maestro-postgres psql -U maestro maestro < "${backupFileName}"`;

  if (language === 'en') {
    return `# Maestro Data Recovery Guide

📅 Backup created: ${dateStr}
💾 Backup file: ${backupFileName}

---

> ⚠️ **Please read before proceeding**
> These steps will overwrite your current Maestro data.
> If you have important data, back it up first before continuing.

---

## 🖥️ Pattern 1: Moving Maestro to a New Computer

Steps to set up Maestro on a new computer and restore your data.

### Step 1: Install Required Software

| Software | Purpose | How to Install |
|----------|---------|----------------|
| Docker Desktop | Run the database | https://www.docker.com/products/docker-desktop/ |
| Node.js (v20+) | Run Maestro | https://nodejs.org/ |
| pnpm | Package manager | \`npm install -g pnpm\` |

### Step 2: Download Maestro

Open Terminal and run:

\`\`\`bash
git clone https://github.com/naotantan/maestro.git
cd maestro
pnpm install
\`\`\`

### Step 3: Copy the Backup File

Copy \`${backupFileName}\` to any folder on your new computer (e.g. Desktop or Downloads).

### Step 4: Start the Database

Make sure Docker Desktop is running, then:

\`\`\`bash
cd maestro
docker compose up -d postgres
\`\`\`

You should see "maestro-postgres  Started".

### Step 5: Restore Your Data

Open Terminal in the folder containing the backup file and run:

\`\`\`bash
${restoreCmd}
\`\`\`

No errors means the restore was successful.

### Step 6: Start Maestro

\`\`\`bash
pnpm dev
\`\`\`

Open \`http://localhost:5173\` in your browser. If your data is there, you're done! 🎉

---

## ⏪ Pattern 2: Rolling Back to a Previous State

Steps to revert Maestro to the state at the time of this backup.

### Step 1: Stop Maestro

Press \`Ctrl + C\` in the terminal where Maestro is running.

### Step 2: Back Up Current Data (Strongly Recommended)

\`\`\`bash
docker exec maestro-postgres pg_dump -U maestro maestro > backup_before_restore_$(date +%Y%m%d%H%M%S).sql
\`\`\`

### Step 3: Restore the Backup

First, clear the current data:

\`\`\`bash
docker exec maestro-postgres psql -U maestro -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;" maestro
\`\`\`

Then restore from the backup:

\`\`\`bash
${restoreCmd}
\`\`\`

### Step 4: Restart Maestro

\`\`\`bash
pnpm dev
\`\`\`

Open \`http://localhost:5173\`. If the data matches the backup time, you're done! 🎉

---

## ❓ Troubleshooting

**"docker: command not found"**
→ Docker Desktop is not installed or not running. Start Docker Desktop and try again.

**"connection refused"**
→ The database is not running. Run \`docker compose up -d postgres\` and try again.

**"permission denied"**
→ Try adding \`sudo\` before the command. E.g.: \`sudo docker exec ...\`

---

*This file was auto-generated by Maestro.*
`;
  }

  if (language === 'zh') {
    return `# Maestro 数据恢复手册

📅 备份创建时间：${dateStr}
💾 备份文件名：${backupFileName}

---

> ⚠️ **操作前请务必确认**
> 执行以下步骤将覆盖当前 Maestro 的所有数据。
> 如有重要数据，请先备份当前数据再进行操作。

---

## 🖥️ 方案一：将 Maestro 迁移到新电脑

在新电脑上部署 Maestro 并恢复历史数据。

### 第一步：安装必要软件

| 软件 | 用途 | 安装方式 |
|------|------|----------|
| Docker Desktop | 运行数据库 | https://www.docker.com/products/docker-desktop/ |
| Node.js（v20 以上） | 运行 Maestro | https://nodejs.org/zh-cn/ |
| pnpm | 包管理工具 | \`npm install -g pnpm\` |

### 第二步：下载 Maestro

打开终端，执行以下命令：

\`\`\`bash
git clone https://github.com/naotantan/maestro.git
cd maestro
pnpm install
\`\`\`

### 第三步：复制备份文件

将备份文件（\`${backupFileName}\`）复制到新电脑的任意文件夹（例如桌面或下载文件夹）。

### 第四步：启动数据库

确保 Docker Desktop 已运行，然后执行：

\`\`\`bash
cd maestro
docker compose up -d postgres
\`\`\`

看到 "maestro-postgres  Started" 即表示成功。

### 第五步：恢复数据

在备份文件所在目录打开终端，执行：

\`\`\`bash
${restoreCmd}
\`\`\`

没有错误信息即表示恢复成功。

### 第六步：启动 Maestro

\`\`\`bash
pnpm dev
\`\`\`

在浏览器中打开 \`http://localhost:5173\`，确认数据已恢复即大功告成！🎉

---

## ⏪ 方案二：回滚到历史数据

将 Maestro 恢复到本备份创建时的状态。

### 第一步：停止 Maestro

在运行 Maestro 的终端中按 \`Ctrl + C\`。

### 第二步：备份当前数据（强烈建议）

\`\`\`bash
docker exec maestro-postgres pg_dump -U maestro maestro > backup_before_restore_$(date +%Y%m%d%H%M%S).sql
\`\`\`

### 第三步：恢复备份数据

先清空当前数据：

\`\`\`bash
docker exec maestro-postgres psql -U maestro -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;" maestro
\`\`\`

再导入备份数据：

\`\`\`bash
${restoreCmd}
\`\`\`

### 第四步：重启 Maestro

\`\`\`bash
pnpm dev
\`\`\`

打开 \`http://localhost:5173\`，确认数据已回到备份时的状态即完成！🎉

---

## ❓ 常见问题

**提示 "docker: command not found"**
→ Docker Desktop 未安装或未启动，请先启动 Docker Desktop 后重试。

**提示 "connection refused"**
→ 数据库未运行，请执行 \`docker compose up -d postgres\` 后重试。

**提示 "permission denied"**
→ 请在命令前加 \`sudo\`，例如：\`sudo docker exec ...\`

---

*本文件由 Maestro 自动生成。*
`;
  }

  return `# Maestro データリカバリ手順書

📅 バックアップ作成日時: ${dateStr}
💾 バックアップファイル名: ${backupFileName}

---

> ⚠️ **作業前に必ず確認してください**
> この手順書の操作を行うと、現在の Maestro のデータが上書きされます。
> 大切なデータがある場合は、先に現在のデータをバックアップしてから作業してください。

---

## 🖥️ パターン1：新しいパソコンに Maestro を移す

新しいパソコンで Maestro を一から動かして、過去のデータを引き継ぐ手順です。

### ステップ1：必要なソフトをインストールする

以下のソフトが必要です。それぞれのリンクからダウンロードしてインストールしてください。

| ソフト | 何に使うか | インストール方法 |
|--------|-----------|-----------------|
| Docker Desktop | データベースの起動 | https://www.docker.com/products/docker-desktop/ |
| Node.js (v20以上) | Maestro の実行 | https://nodejs.org/ja/ |
| pnpm | パッケージ管理 | \`npm install -g pnpm\` |

### ステップ2：Maestro をダウンロードする

ターミナル（Macの場合）またはコマンドプロンプト（Windowsの場合）を開いて、
以下のコマンドをコピーして貼り付け、Enterキーを押してください。

\`\`\`bash
git clone https://github.com/naotantan/maestro.git
cd maestro
pnpm install
\`\`\`

### ステップ3：バックアップファイルをコピーする

このバックアップファイル（\`${backupFileName}\`）を、
新しいパソコンの任意のフォルダに置いてください。
（例：デスクトップや「ダウンロード」フォルダ）

### ステップ4：データベースを起動する

Docker Desktop を起動した状態で、以下のコマンドを実行してください。

\`\`\`bash
cd maestro
docker compose up -d postgres
\`\`\`

「maestro-postgres  Started」と表示されれば成功です。

### ステップ5：データを復元する

バックアップファイルがある場所でターミナルを開き、
以下のコマンドを実行してください。

\`\`\`bash
${restoreCmd}
\`\`\`

コマンドが終わってエラーが表示されなければ、データの復元は完了です。

### ステップ6：Maestro を起動する

\`\`\`bash
pnpm dev
\`\`\`

ブラウザで \`http://localhost:5173\` を開いて、データが戻っていれば成功です！ 🎉

---

## ⏪ パターン2：過去のデータに戻したい（ロールバック）

現在の Maestro で何か問題が起きて、このバックアップを取った時点の状態に戻す手順です。

### ステップ1：Maestro を停止する

現在動いている Maestro のサーバーを止めてください。
ターミナルで \`Ctrl + C\` を押すと停止できます。

### ステップ2：念のため現在のデータをバックアップする（強く推奨）

今のデータを先にバックアップしておくと、万が一失敗しても安心です。

\`\`\`bash
docker exec maestro-postgres pg_dump -U maestro maestro > backup_before_restore_$(date +%Y%m%d%H%M%S).sql
\`\`\`

「backup_before_restore_...」というファイルができれば成功です。

### ステップ3：バックアップファイルを使ってデータを復元する

バックアップファイル（\`${backupFileName}\`）がある場所でターミナルを開き、
以下のコマンドを実行してください。

まず、今のデータを一度空にします。

\`\`\`bash
docker exec maestro-postgres psql -U maestro -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;" maestro
\`\`\`

次に、バックアップのデータを流し込みます。

\`\`\`bash
${restoreCmd}
\`\`\`

エラーが出なければ完了です。

### ステップ4：Maestro を再起動する

\`\`\`bash
pnpm dev
\`\`\`

ブラウザで \`http://localhost:5173\` を開いて、
バックアップを取った時点のデータに戻っていれば成功です！ 🎉

---

## ❓ うまくいかないときは

### よくあるエラーと対処法

**「docker: command not found」と表示される場合**
→ Docker Desktop がインストールされていないか、起動していません。
　 Docker Desktop を起動してから再度お試しください。

**「connection refused」と表示される場合**
→ データベースが起動していません。
　 \`docker compose up -d postgres\` を実行してから再度お試しください。

**「permission denied」と表示される場合**
→ コマンドの前に \`sudo\` を付けて試してください。
　 例：\`sudo docker exec ...\`

---

*このファイルは Maestro によって自動生成されました。*
`;
}

/** pg_dump を実行してバッファを返す */
async function dumpDatabase(): Promise<Buffer> {
  try {
    const { stdout } = await execAsync(
      `docker exec ${PG_CONTAINER} pg_dump -U ${PG_USER} ${PG_DB}`,
      { encoding: 'buffer', maxBuffer: 500 * 1024 * 1024 },
    );
    return stdout as unknown as Buffer;
  } catch (dockerErr) {
    const databaseUrl = process.env.DATABASE_URL;
    if (!databaseUrl) {
      throw new Error(
        `pg_dump の実行に失敗しました。Docker が起動しているか確認してください。\n詳細: ${(dockerErr as Error).message}`,
      );
    }
    const { stdout } = await execAsync(
      `pg_dump "${databaseUrl}"`,
      { encoding: 'buffer', maxBuffer: 500 * 1024 * 1024 },
    );
    return stdout as unknown as Buffer;
  }
}

/** Google Drive にファイルをアップロードする */
async function uploadFile(
  drive: ReturnType<typeof google.drive>,
  filePath: string,
  mimeType: string,
  folderId: string,
): Promise<string> {
  const response = await drive.files.create({
    requestBody: { name: basename(filePath), parents: [folderId] },
    media: { mimeType, body: createReadStream(filePath) },
    fields: 'id, webViewLink',
  });
  return (
    response.data.webViewLink ??
    `https://drive.google.com/file/d/${response.data.id}`
  );
}

export async function runBackup(config: BackupRunConfig): Promise<BackupRunResult> {
  if (!existsSync(BACKUP_DIR)) {
    mkdirSync(BACKUP_DIR, { recursive: true });
  }

  const now = new Date();
  const timestamp = now.toISOString().replace(/[:.]/g, '-');
  const tempSql = join(BACKUP_DIR, `backup-${timestamp}.sql`);

  const dumpData = await dumpDatabase();
  writeFileSync(tempSql, dumpData);

  const useGzip = config.compression === 'gzip';
  const ext = useGzip ? '.sql.gz' : '.sql';
  const outputDir =
    config.destinationType === 'local' && config.localPath
      ? config.localPath
      : BACKUP_DIR;

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const backupFileName = `backup-${timestamp}${ext}`;
  const finalFile = join(outputDir, backupFileName);

  if (useGzip) {
    await pipeline(createReadStream(tempSql), createGzip(), createWriteStream(finalFile));
    unlinkSync(tempSql);
  } else if (finalFile !== tempSql) {
    await pipeline(createReadStream(tempSql), createWriteStream(finalFile));
    unlinkSync(tempSql);
  }

  // リカバリマニュアルを生成
  const manualContent = generateRecoveryManual(backupFileName, now, config.language);
  const manualFileName = `RECOVERY_MANUAL-${timestamp}.md`;
  const manualFile = join(BACKUP_DIR, manualFileName);
  writeFileSync(manualFile, manualContent, 'utf-8');

  if (config.destinationType === 'gdrive') {
    if (!config.gdriveFolderId) {
      throw new Error('Google Drive バックアップには gdriveFolderId が必要です');
    }

    const auth = createGdriveAuth();
    const drive = google.drive({ version: 'v3', auth });

    // バックアップ本体をアップロード
    const driveUrl = await uploadFile(drive, finalFile, 'application/octet-stream', config.gdriveFolderId);
    unlinkSync(finalFile);

    // リカバリマニュアルをアップロード
    const manualDriveUrl = await uploadFile(drive, manualFile, 'text/markdown', config.gdriveFolderId);
    unlinkSync(manualFile);

    return {
      success: true,
      driveUrl,
      manualDriveUrl,
      message: 'Google Drive へのアップロードが完了しました（バックアップ＋リカバリ手順書）',
    };
  }

  // ローカル保存: マニュアルも同じディレクトリへ
  const localManualFile = join(outputDir, manualFileName);
  if (localManualFile !== manualFile) {
    writeFileSync(localManualFile, manualContent, 'utf-8');
    unlinkSync(manualFile);
  }

  return {
    success: true,
    filePath: finalFile,
    message: `バックアップが完了しました（リカバリ手順書も同フォルダに保存済み）`,
  };
}
